In [1]:
import pandas as pd
import numpy as np

In [2]:
orders = pd.read_csv('delivery_orders_march.csv')

In [3]:
orders

,orderid,pick,1st_deliver_attempt,2nd_deliver_attempt,buyeraddress,selleraddress
0,2215676524,1583138397,1.583385e+09,NaN,"Baging ldl BUENAVISTA,PATAG.CAGAYAN Buagsong,c...",Pantranco vill. 417 Warehouse# katipunan 532 (...
1,2219624609,1583309968,1.583463e+09,1.583799e+09,coloma's quzom CASANAS Site1 Masiyan 533A Stol...,"BLDG 210A Moras C42B 2B16,168 church) Complex ..."
2,2220979489,1583306434,1.583460e+09,NaN,"21-O LumangDaan,Capitangan,Abucay,Bataan .Bign...","#66 150-C, DRIVE, Milagros Joe socorro Metro M..."
3,2221066352,1583419016,1.583556e+09,NaN,"616Espiritu MARTINVILLE,MANUYO #5paraiso kengi...","999maII 201,26 Villaruel Barretto gen.t number..."
4,2222478803,1583318305,1.583480e+09,NaN,L042 Summerbreezee1 L2(Balanay analyn Lot760 C...,G66MANILA Hiyas Fitness MAYSILO magdiwang Lt.4...
...,...,...,...,...,...,...
3176308,31504087640510,1585821728,1.585978e+09,NaN,"mayapis. edeliza JC274 5542 brgy.Dita, Metro M...",Intimate St) compound. Sekiat 2B8 98-B Mel far...
3176309,31504147352227,1585895011,1.586179e+09,1.586232e+09,"Superdome PORKY K307 Libertad, PCGCC sub.bagui...","13th 3616 Pilipinas, :1v26 1f-5 (Village) bl10..."
3176310,31504462290482,1585826951,1.585965e+09,NaN,Galay's 1republic 333-18 Diliman 74d Malbay fe...,"Lane, 379B 1739A Ivc AFPFC Cainta, Waterpark, ..."
3176311,31504851495943,1585891194,1.586230e+09,NaN,"#4560, 80south biloca vi!!age KM21, MANRESA, ,...",lrt-2 Consolacion 224-A Paradise 6D 36st champ...
3176312,31505199116340,1585823923,1.586153e+09,1.586231e+09,b4l13 TOLDA 792-A-5-A east...near CARRASCO Ang...,(Jeepney Kaligayan VANVAN Salud ASA Lauan A-55...

In [4]:
# import numpy as np
# np.busday_count(start,end,weekmask=[1,1,1,1,1,1,0],holidays=['2020-03-25','2020-03-30','2020-03-31'])

In [5]:
np.busday_count('2020-03-22','2020-03-27',weekmask=[1,1,1,1,1,1,0],holidays=['2020-03-25','2020-03-30','2020-03-31'])

3

In [6]:
from datetime import datetime
orders['dt_pick'] = pd.to_datetime(orders['pick'],unit='s')
orders['dt_1st_deliver_attempt'] = pd.to_datetime(orders['1st_deliver_attempt'],unit='s')
orders['dt_2nd_deliver_attempt'] = pd.to_datetime(orders['2nd_deliver_attempt'],unit='s')

In [7]:
orders

,orderid,pick,1st_deliver_attempt,2nd_deliver_attempt,buyeraddress,selleraddress,dt_pick,dt_1st_deliver_attempt,dt_2nd_deliver_attempt
0,2215676524,1583138397,1.583385e+09,NaN,"Baging ldl BUENAVISTA,PATAG.CAGAYAN Buagsong,c...",Pantranco vill. 417 Warehouse# katipunan 532 (...,2020-03-02 08:39:57,2020-03-05 05:09:18,NaT
1,2219624609,1583309968,1.583463e+09,1.583799e+09,coloma's quzom CASANAS Site1 Masiyan 533A Stol...,"BLDG 210A Moras C42B 2B16,168 church) Complex ...",2020-03-04 08:19:28,2020-03-06 02:53:56,2020-03-10 00:02:56
2,2220979489,1583306434,1.583460e+09,NaN,"21-O LumangDaan,Capitangan,Abucay,Bataan .Bign...","#66 150-C, DRIVE, Milagros Joe socorro Metro M...",2020-03-04 07:20:34,2020-03-06 01:56:19,NaT
3,2221066352,1583419016,1.583556e+09,NaN,"616Espiritu MARTINVILLE,MANUYO #5paraiso kengi...","999maII 201,26 Villaruel Barretto gen.t number...",2020-03-05 14:36:56,2020-03-07 04:45:41,NaT
4,2222478803,1583318305,1.583480e+09,NaN,L042 Summerbreezee1 L2(Balanay analyn Lot760 C...,G66MANILA Hiyas Fitness MAYSILO magdiwang Lt.4...,2020-03-04 10:38:25,2020-03-06 07:41:40,NaT
...,...,...,...,...,...,...,...,...,...
3176308,31504087640510,1585821728,1.585978e+09,NaN,"mayapis. edeliza JC274 5542 brgy.Dita, Metro M...",Intimate St) compound. Sekiat 2B8 98-B Mel far...,2020-04-02 10:02:08,2020-04-04 05:22:22,NaT
3176309,31504147352227,1585895011,1.586179e+09,1.586232e+09,"Superdome PORKY K307 Libertad, PCGCC sub.bagui...","13th 3616 Pilipinas, :1v26 1f-5 (Village) bl10...",2020-04-03 06:23:31,2020-04-06 13:17:27,2020-04-07 03:52:11
3176310,31504462290482,1585826951,1.585965e+09,NaN,Galay's 1republic 333-18 Diliman 74d Malbay fe...,"Lane, 379B 1739A Ivc AFPFC Cainta, Waterpark, ...",2020-04-02 11:29:11,2020-04-04 01:55:40,NaT
3176311,31504851495943,1585891194,1.586230e+09,NaN,"#4560, 80south biloca vi!!age KM21, MANRESA, ,...",lrt-2 Consolacion 224-A Paradise 6D 36st champ...,2020-04-03 05:19:54,2020-04-07 03:19:12,NaT
3176312,31505199116340,1585823923,1.586153e+09,1.586231e+09,b4l13 TOLDA 792-A-5-A east...near CARRASCO Ang...,(Jeepney Kaligayan VANVAN Salud ASA Lauan A-55...,2020-04-02 10:38:43,2020-04-06 06:02:22,2020-04-07 03:37:20

In [8]:
orders['dt_pick'] = orders['dt_pick'].dt.date
orders['dt_1st_deliver_attempt'] = orders['dt_1st_deliver_attempt'].dt.date
orders['dt_2nd_deliver_attempt'] = orders['dt_2nd_deliver_attempt'].dt.date
orders

,orderid,pick,1st_deliver_attempt,2nd_deliver_attempt,buyeraddress,selleraddress,dt_pick,dt_1st_deliver_attempt,dt_2nd_deliver_attempt
0,2215676524,1583138397,1.583385e+09,NaN,"Baging ldl BUENAVISTA,PATAG.CAGAYAN Buagsong,c...",Pantranco vill. 417 Warehouse# katipunan 532 (...,2020-03-02,2020-03-05,NaT
1,2219624609,1583309968,1.583463e+09,1.583799e+09,coloma's quzom CASANAS Site1 Masiyan 533A Stol...,"BLDG 210A Moras C42B 2B16,168 church) Complex ...",2020-03-04,2020-03-06,2020-03-10
2,2220979489,1583306434,1.583460e+09,NaN,"21-O LumangDaan,Capitangan,Abucay,Bataan .Bign...","#66 150-C, DRIVE, Milagros Joe socorro Metro M...",2020-03-04,2020-03-06,NaT
3,2221066352,1583419016,1.583556e+09,NaN,"616Espiritu MARTINVILLE,MANUYO #5paraiso kengi...","999maII 201,26 Villaruel Barretto gen.t number...",2020-03-05,2020-03-07,NaT
4,2222478803,1583318305,1.583480e+09,NaN,L042 Summerbreezee1 L2(Balanay analyn Lot760 C...,G66MANILA Hiyas Fitness MAYSILO magdiwang Lt.4...,2020-03-04,2020-03-06,NaT
...,...,...,...,...,...,...,...,...,...
3176308,31504087640510,1585821728,1.585978e+09,NaN,"mayapis. edeliza JC274 5542 brgy.Dita, Metro M...",Intimate St) compound. Sekiat 2B8 98-B Mel far...,2020-04-02,2020-04-04,NaT
3176309,31504147352227,1585895011,1.586179e+09,1.586232e+09,"Superdome PORKY K307 Libertad, PCGCC sub.bagui...","13th 3616 Pilipinas, :1v26 1f-5 (Village) bl10...",2020-04-03,2020-04-06,2020-04-07
3176310,31504462290482,1585826951,1.585965e+09,NaN,Galay's 1republic 333-18 Diliman 74d Malbay fe...,"Lane, 379B 1739A Ivc AFPFC Cainta, Waterpark, ...",2020-04-02,2020-04-04,NaT
3176311,31504851495943,1585891194,1.586230e+09,NaN,"#4560, 80south biloca vi!!age KM21, MANRESA, ,...",lrt-2 Consolacion 224-A Paradise 6D 36st champ...,2020-04-03,2020-04-07,NaT
3176312,31505199116340,1585823923,1.586153e+09,1.586231e+09,b4l13 TOLDA 792-A-5-A east...near CARRASCO Ang...,(Jeepney Kaligayan VANVAN Salud ASA Lauan A-55...,2020-04-02,2020-04-06,2020-04-07

In [9]:
def busday(start, end):
    return np.busday_count(start,end,weekmask=[1,1,1,1,1,1,0],holidays=['2020-03-25','2020-03-30','2020-03-31'])

In [10]:
orders['1st_del_busday'] = np.vectorize(busday)(orders['dt_pick'], orders['dt_1st_deliver_attempt'])
orders

,orderid,pick,1st_deliver_attempt,2nd_deliver_attempt,buyeraddress,selleraddress,dt_pick,dt_1st_deliver_attempt,dt_2nd_deliver_attempt,1st_del_busday
0,2215676524,1583138397,1.583385e+09,NaN,"Baging ldl BUENAVISTA,PATAG.CAGAYAN Buagsong,c...",Pantranco vill. 417 Warehouse# katipunan 532 (...,2020-03-02,2020-03-05,NaT,3
1,2219624609,1583309968,1.583463e+09,1.583799e+09,coloma's quzom CASANAS Site1 Masiyan 533A Stol...,"BLDG 210A Moras C42B 2B16,168 church) Complex ...",2020-03-04,2020-03-06,2020-03-10,2
2,2220979489,1583306434,1.583460e+09,NaN,"21-O LumangDaan,Capitangan,Abucay,Bataan .Bign...","#66 150-C, DRIVE, Milagros Joe socorro Metro M...",2020-03-04,2020-03-06,NaT,2
3,2221066352,1583419016,1.583556e+09,NaN,"616Espiritu MARTINVILLE,MANUYO #5paraiso kengi...","999maII 201,26 Villaruel Barretto gen.t number...",2020-03-05,2020-03-07,NaT,2
4,2222478803,1583318305,1.583480e+09,NaN,L042 Summerbreezee1 L2(Balanay analyn Lot760 C...,G66MANILA Hiyas Fitness MAYSILO magdiwang Lt.4...,2020-03-04,2020-03-06,NaT,2
...,...,...,...,...,...,...,...,...,...,...
3176308,31504087640510,1585821728,1.585978e+09,NaN,"mayapis. edeliza JC274 5542 brgy.Dita, Metro M...",Intimate St) compound. Sekiat 2B8 98-B Mel far...,2020-04-02,2020-04-04,NaT,2
3176309,31504147352227,1585895011,1.586179e+09,1.586232e+09,"Superdome PORKY K307 Libertad, PCGCC sub.bagui...","13th 3616 Pilipinas, :1v26 1f-5 (Village) bl10...",2020-04-03,2020-04-06,2020-04-07,2
3176310,31504462290482,1585826951,1.585965e+09,NaN,Galay's 1republic 333-18 Diliman 74d Malbay fe...,"Lane, 379B 1739A Ivc AFPFC Cainta, Waterpark, ...",2020-04-02,2020-04-04,NaT,2
3176311,31504851495943,1585891194,1.586230e+09,NaN,"#4560, 80south biloca vi!!age KM21, MANRESA, ,...",lrt-2 Consolacion 224-A Paradise 6D 36st champ...,2020-04-03,2020-04-07,NaT,3
3176312,31505199116340,1585823923,1.586153e+09,1.586231e+09,b4l13 TOLDA 792-A-5-A east...near CARRASCO Ang...,(Jeepney Kaligayan VANVAN Salud ASA Lauan A-55...,2020-04-02,2020-04-06,2020-04-07,3

In [11]:
orders['dt_2nd_del_att'] = orders.dt_2nd_deliver_attempt.astype(object).where(orders.dt_2nd_deliver_attempt.notnull(), None)

In [12]:
def busday(start, end):
    if end is not None:
        return np.busday_count(start,end,weekmask=[1,1,1,1,1,1,0],holidays=['2020-03-25','2020-03-30','2020-03-31'])

In [13]:
orders['2nd_del_busday'] = np.vectorize(busday)(orders['dt_1st_deliver_attempt'], orders['dt_2nd_del_att'])
orders

,orderid,pick,1st_deliver_attempt,2nd_deliver_attempt,buyeraddress,selleraddress,dt_pick,dt_1st_deliver_attempt,dt_2nd_deliver_attempt,1st_del_busday,dt_2nd_del_att,2nd_del_busday
0,2215676524,1583138397,1.583385e+09,NaN,"Baging ldl BUENAVISTA,PATAG.CAGAYAN Buagsong,c...",Pantranco vill. 417 Warehouse# katipunan 532 (...,2020-03-02,2020-03-05,NaT,3,None,None
1,2219624609,1583309968,1.583463e+09,1.583799e+09,coloma's quzom CASANAS Site1 Masiyan 533A Stol...,"BLDG 210A Moras C42B 2B16,168 church) Complex ...",2020-03-04,2020-03-06,2020-03-10,2,2020-03-10,3
2,2220979489,1583306434,1.583460e+09,NaN,"21-O LumangDaan,Capitangan,Abucay,Bataan .Bign...","#66 150-C, DRIVE, Milagros Joe socorro Metro M...",2020-03-04,2020-03-06,NaT,2,None,None
3,2221066352,1583419016,1.583556e+09,NaN,"616Espiritu MARTINVILLE,MANUYO #5paraiso kengi...","999maII 201,26 Villaruel Barretto gen.t number...",2020-03-05,2020-03-07,NaT,2,None,None
4,2222478803,1583318305,1.583480e+09,NaN,L042 Summerbreezee1 L2(Balanay analyn Lot760 C...,G66MANILA Hiyas Fitness MAYSILO magdiwang Lt.4...,2020-03-04,2020-03-06,NaT,2,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
3176308,31504087640510,1585821728,1.585978e+09,NaN,"mayapis. edeliza JC274 5542 brgy.Dita, Metro M...",Intimate St) compound. Sekiat 2B8 98-B Mel far...,2020-04-02,2020-04-04,NaT,2,None,None
3176309,31504147352227,1585895011,1.586179e+09,1.586232e+09,"Superdome PORKY K307 Libertad, PCGCC sub.bagui...","13th 3616 Pilipinas, :1v26 1f-5 (Village) bl10...",2020-04-03,2020-04-06,2020-04-07,2,2020-04-07,1
3176310,31504462290482,1585826951,1.585965e+09,NaN,Galay's 1republic 333-18 Diliman 74d Malbay fe...,"Lane, 379B 1739A Ivc AFPFC Cainta, Waterpark, ...",2020-04-02,2020-04-04,NaT,2,None,None
3176311,31504851495943,1585891194,1.586230e+09,NaN,"#4560, 80south biloca vi!!age KM21, MANRESA, ,...",lrt-2 Consolacion 224-A Paradise 6D 36st champ...,2020-04-03,2020-04-07,NaT,3,None,None
3176312,31505199116340,1585823923,1.586153e+09,1.586231e+09,b4l13 TOLDA 792-A-5-A east...near CARRASCO Ang...,(Jeepney Kaligayan VANVAN Salud ASA Lauan A-55...,2020-04-02,2020-04-06,2020-04-07,3,2020-04-07,1

In [14]:
df_split = np.array_split(orders, 10)
first = df_split[0]

In [15]:
first

,orderid,pick,1st_deliver_attempt,2nd_deliver_attempt,buyeraddress,selleraddress,dt_pick,dt_1st_deliver_attempt,dt_2nd_deliver_attempt,1st_del_busday,dt_2nd_del_att,2nd_del_busday
0,2215676524,1583138397,1.583385e+09,NaN,"Baging ldl BUENAVISTA,PATAG.CAGAYAN Buagsong,c...",Pantranco vill. 417 Warehouse# katipunan 532 (...,2020-03-02,2020-03-05,NaT,3,None,None
1,2219624609,1583309968,1.583463e+09,1.583799e+09,coloma's quzom CASANAS Site1 Masiyan 533A Stol...,"BLDG 210A Moras C42B 2B16,168 church) Complex ...",2020-03-04,2020-03-06,2020-03-10,2,2020-03-10,3
2,2220979489,1583306434,1.583460e+09,NaN,"21-O LumangDaan,Capitangan,Abucay,Bataan .Bign...","#66 150-C, DRIVE, Milagros Joe socorro Metro M...",2020-03-04,2020-03-06,NaT,2,None,None
3,2221066352,1583419016,1.583556e+09,NaN,"616Espiritu MARTINVILLE,MANUYO #5paraiso kengi...","999maII 201,26 Villaruel Barretto gen.t number...",2020-03-05,2020-03-07,NaT,2,None,None
4,2222478803,1583318305,1.583480e+09,NaN,L042 Summerbreezee1 L2(Balanay analyn Lot760 C...,G66MANILA Hiyas Fitness MAYSILO magdiwang Lt.4...,2020-03-04,2020-03-06,NaT,2,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
317627,2227960081,1583136333,1.583383e+09,NaN,"Magtangob Isidro,Buhangin vettalea entrance/ s...",Festival starbucks Bethlehem ci 62-A MiLenyo M...,2020-03-02,2020-03-05,NaT,3,None,None
317628,2227969153,1583138450,1.583289e+09,NaN,"CENTRO,TABUK P3-C, paros #blk1 Republic PAGNAN...",Bank-Karuhatan ELem.School flexihomes Warehous...,2020-03-02,2020-03-04,NaT,2,None,None
317629,2227975558,1583313191,1.583568e+09,NaN,"Inc.304 Dayasan, Unit26 Flerida 7,blk.134 Metr...",aq CLOSED Rasco (Team (2nd Aguarra Metro Manila,2020-03-04,2020-03-07,NaT,3,None,None
317630,2227977623,1583311762,1.583986e+09,NaN,"Pert Mb27 Blockk6 St,Angeles bonifacio292caban...",Castro 195 PRIVATE 805B #47 Z (LANE Metro Manila,2020-03-04,2020-03-12,NaT,7,None,None
317631,2227994495,1583141331,1.583292e+09,NaN,"H-M.L Zalameda (DP) street,san NETHSPA ciniple...",Brgy.306 jem #717 catolos st.barangay bejo Cam...,2020-03-02,2020-03-04,NaT,2,None,None

In [16]:
import re

In [17]:
countries = ['Metro Manila', 'Luzon', 'Visayas', 'Mindanao']

In [18]:
first['buyeraddress'] = first['buyeraddress'].str.lower()

first['selleraddress'] = first['selleraddress'].str.lower()

In [19]:
orders['buyeraddress'] = orders['buyeraddress'].str.lower()

orders['selleraddress'] = orders['selleraddress'].str.lower()

In [20]:
first['destination'] = first['buyeraddress'].apply(lambda x: 'metro manila' if 'metro manila' in x 
                                                             else ('luzon' if 'luzon' in x
                                                                    else ('visayas' if 'visayas' in x
                                                                          else 'mindanao')))
first['origin'] = first['selleraddress'].apply(lambda x: 'metro manila' if 'metro manila' in x 
                                                             else ('luzon' if 'luzon' in x
                                                                    else ('visayas' if 'visayas' in x
                                                                          else 'mindanao')))

In [21]:
orders['destination'] = orders['buyeraddress'].apply(lambda x: 'metro manila' if 'metro manila' in x 
                                                             else ('luzon' if 'luzon' in x
                                                                    else ('visayas' if 'visayas' in x
                                                                          else 'mindanao')))
orders['origin'] = orders['selleraddress'].apply(lambda x: 'metro manila' if 'metro manila' in x 
                                                             else ('luzon' if 'luzon' in x
                                                                    else ('visayas' if 'visayas' in x
                                                                          else 'mindanao')))

In [22]:
first

,orderid,pick,1st_deliver_attempt,2nd_deliver_attempt,buyeraddress,selleraddress,dt_pick,dt_1st_deliver_attempt,dt_2nd_deliver_attempt,1st_del_busday,dt_2nd_del_att,2nd_del_busday,destination,origin
0,2215676524,1583138397,1.583385e+09,NaN,"baging ldl buenavista,patag.cagayan buagsong,c...",pantranco vill. 417 warehouse# katipunan 532 (...,2020-03-02,2020-03-05,NaT,3,None,None,metro manila,metro manila
1,2219624609,1583309968,1.583463e+09,1.583799e+09,coloma's quzom casanas site1 masiyan 533a stol...,"bldg 210a moras c42b 2b16,168 church) complex ...",2020-03-04,2020-03-06,2020-03-10,2,2020-03-10,3,metro manila,metro manila
2,2220979489,1583306434,1.583460e+09,NaN,"21-o lumangdaan,capitangan,abucay,bataan .bign...","#66 150-c, drive, milagros joe socorro metro m...",2020-03-04,2020-03-06,NaT,2,None,None,metro manila,metro manila
3,2221066352,1583419016,1.583556e+09,NaN,"616espiritu martinville,manuyo #5paraiso kengi...","999maii 201,26 villaruel barretto gen.t number...",2020-03-05,2020-03-07,NaT,2,None,None,metro manila,metro manila
4,2222478803,1583318305,1.583480e+09,NaN,l042 summerbreezee1 l2(balanay analyn lot760 c...,g66manila hiyas fitness maysilo magdiwang lt.4...,2020-03-04,2020-03-06,NaT,2,None,None,luzon,metro manila
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317627,2227960081,1583136333,1.583383e+09,NaN,"magtangob isidro,buhangin vettalea entrance/ s...",festival starbucks bethlehem ci 62-a milenyo m...,2020-03-02,2020-03-05,NaT,3,None,None,luzon,metro manila
317628,2227969153,1583138450,1.583289e+09,NaN,"centro,tabuk p3-c, paros #blk1 republic pagnan...",bank-karuhatan elem.school flexihomes warehous...,2020-03-02,2020-03-04,NaT,2,None,None,metro manila,metro manila
317629,2227975558,1583313191,1.583568e+09,NaN,"inc.304 dayasan, unit26 flerida 7,blk.134 metr...",aq closed rasco (team (2nd aguarra metro manila,2020-03-04,2020-03-07,NaT,3,None,None,metro manila,metro manila
317630,2227977623,1583311762,1.583986e+09,NaN,"pert mb27 blockk6 st,angeles bonifacio292caban...",castro 195 private 805b #47 z (lane metro manila,2020-03-04,2020-03-12,NaT,7,None,None,mindanao,metro manila
317631,2227994495,1583141331,1.583292e+09,NaN,"h-m.l zalameda (dp) street,san nethspa ciniple...",brgy.306 jem #717 catolos st.barangay bejo cam...,2020-03-02,2020-03-04,NaT,2,None,None,metro manila,metro manila

In [23]:
sla_targets = [[3,5,7,7],
              [5,5,7,7],
              [7,7,7,7],
              [7,7,7,7]]

In [24]:
def det_country_index(country):
    if (country == 'metro manila'):
        return 0
    elif(country=='luzon'):
        return 1
    elif(country=='visayas'):
        return 2
    elif(country=='mindanao'):
        return 3

In [25]:
def determine_sla_target(origin, destination):
    orig_ind = det_country_index(origin)
    dest_ind = det_country_index(destination)
    return sla_targets[orig_ind][dest_ind]

In [26]:
determine_sla_target('metro manila', 'visayas')

7

In [27]:
first['sla_target'] = np.vectorize(determine_sla_target)(first['origin'], first['destination'])

In [28]:
orders['sla_target'] = np.vectorize(determine_sla_target)(orders['origin'], orders['destination'])

In [29]:
first

,orderid,pick,1st_deliver_attempt,2nd_deliver_attempt,buyeraddress,selleraddress,dt_pick,dt_1st_deliver_attempt,dt_2nd_deliver_attempt,1st_del_busday,dt_2nd_del_att,2nd_del_busday,destination,origin,sla_target
0,2215676524,1583138397,1.583385e+09,NaN,"baging ldl buenavista,patag.cagayan buagsong,c...",pantranco vill. 417 warehouse# katipunan 532 (...,2020-03-02,2020-03-05,NaT,3,None,None,metro manila,metro manila,3
1,2219624609,1583309968,1.583463e+09,1.583799e+09,coloma's quzom casanas site1 masiyan 533a stol...,"bldg 210a moras c42b 2b16,168 church) complex ...",2020-03-04,2020-03-06,2020-03-10,2,2020-03-10,3,metro manila,metro manila,3
2,2220979489,1583306434,1.583460e+09,NaN,"21-o lumangdaan,capitangan,abucay,bataan .bign...","#66 150-c, drive, milagros joe socorro metro m...",2020-03-04,2020-03-06,NaT,2,None,None,metro manila,metro manila,3
3,2221066352,1583419016,1.583556e+09,NaN,"616espiritu martinville,manuyo #5paraiso kengi...","999maii 201,26 villaruel barretto gen.t number...",2020-03-05,2020-03-07,NaT,2,None,None,metro manila,metro manila,3
4,2222478803,1583318305,1.583480e+09,NaN,l042 summerbreezee1 l2(balanay analyn lot760 c...,g66manila hiyas fitness maysilo magdiwang lt.4...,2020-03-04,2020-03-06,NaT,2,None,None,luzon,metro manila,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317627,2227960081,1583136333,1.583383e+09,NaN,"magtangob isidro,buhangin vettalea entrance/ s...",festival starbucks bethlehem ci 62-a milenyo m...,2020-03-02,2020-03-05,NaT,3,None,None,luzon,metro manila,5
317628,2227969153,1583138450,1.583289e+09,NaN,"centro,tabuk p3-c, paros #blk1 republic pagnan...",bank-karuhatan elem.school flexihomes warehous...,2020-03-02,2020-03-04,NaT,2,None,None,metro manila,metro manila,3
317629,2227975558,1583313191,1.583568e+09,NaN,"inc.304 dayasan, unit26 flerida 7,blk.134 metr...",aq closed rasco (team (2nd aguarra metro manila,2020-03-04,2020-03-07,NaT,3,None,None,metro manila,metro manila,3
317630,2227977623,1583311762,1.583986e+09,NaN,"pert mb27 blockk6 st,angeles bonifacio292caban...",castro 195 private 805b #47 z (lane metro manila,2020-03-04,2020-03-12,NaT,7,None,None,mindanao,metro manila,7
317631,2227994495,1583141331,1.583292e+09,NaN,"h-m.l zalameda (dp) street,san nethspa ciniple...",brgy.306 jem #717 catolos st.barangay bejo cam...,2020-03-02,2020-03-04,NaT,2,None,None,metro manila,metro manila,3

In [30]:
orders

,orderid,pick,1st_deliver_attempt,2nd_deliver_attempt,buyeraddress,selleraddress,dt_pick,dt_1st_deliver_attempt,dt_2nd_deliver_attempt,1st_del_busday,dt_2nd_del_att,2nd_del_busday,destination,origin,sla_target
0,2215676524,1583138397,1.583385e+09,NaN,"baging ldl buenavista,patag.cagayan buagsong,c...",pantranco vill. 417 warehouse# katipunan 532 (...,2020-03-02,2020-03-05,NaT,3,None,None,metro manila,metro manila,3
1,2219624609,1583309968,1.583463e+09,1.583799e+09,coloma's quzom casanas site1 masiyan 533a stol...,"bldg 210a moras c42b 2b16,168 church) complex ...",2020-03-04,2020-03-06,2020-03-10,2,2020-03-10,3,metro manila,metro manila,3
2,2220979489,1583306434,1.583460e+09,NaN,"21-o lumangdaan,capitangan,abucay,bataan .bign...","#66 150-c, drive, milagros joe socorro metro m...",2020-03-04,2020-03-06,NaT,2,None,None,metro manila,metro manila,3
3,2221066352,1583419016,1.583556e+09,NaN,"616espiritu martinville,manuyo #5paraiso kengi...","999maii 201,26 villaruel barretto gen.t number...",2020-03-05,2020-03-07,NaT,2,None,None,metro manila,metro manila,3
4,2222478803,1583318305,1.583480e+09,NaN,l042 summerbreezee1 l2(balanay analyn lot760 c...,g66manila hiyas fitness maysilo magdiwang lt.4...,2020-03-04,2020-03-06,NaT,2,None,None,luzon,metro manila,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3176308,31504087640510,1585821728,1.585978e+09,NaN,"mayapis. edeliza jc274 5542 brgy.dita, metro m...",intimate st) compound. sekiat 2b8 98-b mel far...,2020-04-02,2020-04-04,NaT,2,None,None,metro manila,metro manila,3
3176309,31504147352227,1585895011,1.586179e+09,1.586232e+09,"superdome porky k307 libertad, pcgcc sub.bagui...","13th 3616 pilipinas, :1v26 1f-5 (village) bl10...",2020-04-03,2020-04-06,2020-04-07,2,2020-04-07,1,metro manila,metro manila,3
3176310,31504462290482,1585826951,1.585965e+09,NaN,galay's 1republic 333-18 diliman 74d malbay fe...,"lane, 379b 1739a ivc afpfc cainta, waterpark, ...",2020-04-02,2020-04-04,NaT,2,None,None,metro manila,metro manila,3
3176311,31504851495943,1585891194,1.586230e+09,NaN,"#4560, 80south biloca vi!!age km21, manresa, ,...",lrt-2 consolacion 224-a paradise 6d 36st champ...,2020-04-03,2020-04-07,NaT,3,None,None,luzon,metro manila,5
3176312,31505199116340,1585823923,1.586153e+09,1.586231e+09,b4l13 tolda 792-a-5-a east...near carrasco ang...,(jeepney kaligayan vanvan salud asa lauan a-55...,2020-04-02,2020-04-06,2020-04-07,3,2020-04-07,1,luzon,metro manila,5

In [31]:
def is_late_calc(first_del, second_del, sla):
    if second_del == None:
        if (first_del>sla):
            return 1
        else:
            return 0
    else:
        if((first_del<=sla) and (second_del<=3)):
            return 0
        else:
            return 1

In [32]:
first['is_late'] = np.vectorize(is_late_calc)(first['1st_del_busday'], first['2nd_del_busday'], first['sla_target'])

In [33]:
orders['is_late'] = np.vectorize(is_late_calc)(orders['1st_del_busday'], orders['2nd_del_busday'], orders['sla_target'])

In [34]:
first

,orderid,pick,1st_deliver_attempt,2nd_deliver_attempt,buyeraddress,selleraddress,dt_pick,dt_1st_deliver_attempt,dt_2nd_deliver_attempt,1st_del_busday,dt_2nd_del_att,2nd_del_busday,destination,origin,sla_target,is_late
0,2215676524,1583138397,1.583385e+09,NaN,"baging ldl buenavista,patag.cagayan buagsong,c...",pantranco vill. 417 warehouse# katipunan 532 (...,2020-03-02,2020-03-05,NaT,3,None,None,metro manila,metro manila,3,0
1,2219624609,1583309968,1.583463e+09,1.583799e+09,coloma's quzom casanas site1 masiyan 533a stol...,"bldg 210a moras c42b 2b16,168 church) complex ...",2020-03-04,2020-03-06,2020-03-10,2,2020-03-10,3,metro manila,metro manila,3,0
2,2220979489,1583306434,1.583460e+09,NaN,"21-o lumangdaan,capitangan,abucay,bataan .bign...","#66 150-c, drive, milagros joe socorro metro m...",2020-03-04,2020-03-06,NaT,2,None,None,metro manila,metro manila,3,0
3,2221066352,1583419016,1.583556e+09,NaN,"616espiritu martinville,manuyo #5paraiso kengi...","999maii 201,26 villaruel barretto gen.t number...",2020-03-05,2020-03-07,NaT,2,None,None,metro manila,metro manila,3,0
4,2222478803,1583318305,1.583480e+09,NaN,l042 summerbreezee1 l2(balanay analyn lot760 c...,g66manila hiyas fitness maysilo magdiwang lt.4...,2020-03-04,2020-03-06,NaT,2,None,None,luzon,metro manila,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317627,2227960081,1583136333,1.583383e+09,NaN,"magtangob isidro,buhangin vettalea entrance/ s...",festival starbucks bethlehem ci 62-a milenyo m...,2020-03-02,2020-03-05,NaT,3,None,None,luzon,metro manila,5,0
317628,2227969153,1583138450,1.583289e+09,NaN,"centro,tabuk p3-c, paros #blk1 republic pagnan...",bank-karuhatan elem.school flexihomes warehous...,2020-03-02,2020-03-04,NaT,2,None,None,metro manila,metro manila,3,0
317629,2227975558,1583313191,1.583568e+09,NaN,"inc.304 dayasan, unit26 flerida 7,blk.134 metr...",aq closed rasco (team (2nd aguarra metro manila,2020-03-04,2020-03-07,NaT,3,None,None,metro manila,metro manila,3,0
317630,2227977623,1583311762,1.583986e+09,NaN,"pert mb27 blockk6 st,angeles bonifacio292caban...",castro 195 private 805b #47 z (lane metro manila,2020-03-04,2020-03-12,NaT,7,None,None,mindanao,metro manila,7,0
317631,2227994495,1583141331,1.583292e+09,NaN,"h-m.l zalameda (dp) street,san nethspa ciniple...",brgy.306 jem #717 catolos st.barangay bejo cam...,2020-03-02,2020-03-04,NaT,2,None,None,metro manila,metro manila,3,0

In [35]:
first.loc[first['is_late']==1]

,orderid,pick,1st_deliver_attempt,2nd_deliver_attempt,buyeraddress,selleraddress,dt_pick,dt_1st_deliver_attempt,dt_2nd_deliver_attempt,1st_del_busday,dt_2nd_del_att,2nd_del_busday,destination,origin,sla_target,is_late
7,2224695304,1583127841,1.583837e+09,NaN,reel zambo.ciyy puyat.cor road/infront #129a l...,polar 75 mulawinan 1g-3 seÃ±ora text/call 2p-01...,2020-03-02,2020-03-10,NaT,7,None,None,metro manila,metro manila,3,1
19,2227790841,1583127051,1.583823e+09,1.584519e+09,lot16a lgc 833.e danica.. matirem jdel bulango...,"duhat asia, landcom sapang lt25 1015 (kl 294 c...",2020-03-02,2020-03-10,2020-03-18,7,2020-03-18,7,mindanao,metro manila,7,1
21,2227816770,1583119714,1.583470e+09,1.583560e+09,"alejandrea ic-15 building,angliongto ,brgy.pad...",5th redwood fabian k-6th allah rm.405 afpovai ...,2020-03-02,2020-03-06,2020-03-07,4,2020-03-07,1,metro manila,metro manila,3,1
22,2227817800,1583140095,1.583888e+09,NaN,store&first v.ortega purityville leblanc visayas,cmpd. love 2024 package cesar 379b lamar manil...,2020-03-02,2020-03-11,NaT,8,None,None,visayas,metro manila,7,1
24,2227831996,1583117606,1.583469e+09,1.583806e+09,naasag entrance)-seaside 414-c experiment brgy...,"ester omega c.m.recto bebot ususan, name quite...",2020-03-02,2020-03-06,2020-03-10,4,2020-03-10,3,metro manila,metro manila,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317599,2227815961,1583146676,1.584004e+09,1.584066e+09,"st.pandacan bldg.53 ilalim,olongapo jun/ronald...","8floor (mikhaila #223 court, 2169 bandino new#...",2020-03-02,2020-03-12,2020-03-13,9,2020-03-13,1,mindanao,metro manila,7,1
317604,2227844664,1583122555,1.583467e+09,NaN,"patawag blvd.,laguna l42, jollibeee tormis (gd...","1r04, logestic airbase ldc 10-d manalo l23 bah...",2020-03-02,2020-03-06,NaT,4,None,None,metro manila,metro manila,3,1
317606,2227851571,1583136887,1.583569e+09,NaN,emeraldstreet brgy.567 mabinuligon. bonganay [...,cmpd. jenkinsen 817-a i/li st.baclaran b.e.k 4...,2020-03-02,2020-03-07,NaT,5,None,None,metro manila,metro manila,3,1
317607,2227853110,1583333338,1.584157e+09,1.584519e+09,"isidro,nueva 6,providence,balabag,pavia,iloilo...",stronghold binay tan mall(bldg2) software g-10...,2020-03-04,2020-03-14,2020-03-18,9,2020-03-18,3,mindanao,metro manila,7,1
317618,2227923787,1583128324,1.583210e+09,1.583547e+09,"bolonsori codova, binondo. humay sta.ana,tagui...",sicaba escriva shoppy 1v10.12 612b 7b03 #47 ta...,2020-03-02,2020-03-03,2020-03-07,1,2020-03-07,4,metro manila,metro manila,3,1

In [36]:
orders

,orderid,pick,1st_deliver_attempt,2nd_deliver_attempt,buyeraddress,selleraddress,dt_pick,dt_1st_deliver_attempt,dt_2nd_deliver_attempt,1st_del_busday,dt_2nd_del_att,2nd_del_busday,destination,origin,sla_target,is_late
0,2215676524,1583138397,1.583385e+09,NaN,"baging ldl buenavista,patag.cagayan buagsong,c...",pantranco vill. 417 warehouse# katipunan 532 (...,2020-03-02,2020-03-05,NaT,3,None,None,metro manila,metro manila,3,0
1,2219624609,1583309968,1.583463e+09,1.583799e+09,coloma's quzom casanas site1 masiyan 533a stol...,"bldg 210a moras c42b 2b16,168 church) complex ...",2020-03-04,2020-03-06,2020-03-10,2,2020-03-10,3,metro manila,metro manila,3,0
2,2220979489,1583306434,1.583460e+09,NaN,"21-o lumangdaan,capitangan,abucay,bataan .bign...","#66 150-c, drive, milagros joe socorro metro m...",2020-03-04,2020-03-06,NaT,2,None,None,metro manila,metro manila,3,0
3,2221066352,1583419016,1.583556e+09,NaN,"616espiritu martinville,manuyo #5paraiso kengi...","999maii 201,26 villaruel barretto gen.t number...",2020-03-05,2020-03-07,NaT,2,None,None,metro manila,metro manila,3,0
4,2222478803,1583318305,1.583480e+09,NaN,l042 summerbreezee1 l2(balanay analyn lot760 c...,g66manila hiyas fitness maysilo magdiwang lt.4...,2020-03-04,2020-03-06,NaT,2,None,None,luzon,metro manila,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3176308,31504087640510,1585821728,1.585978e+09,NaN,"mayapis. edeliza jc274 5542 brgy.dita, metro m...",intimate st) compound. sekiat 2b8 98-b mel far...,2020-04-02,2020-04-04,NaT,2,None,None,metro manila,metro manila,3,0
3176309,31504147352227,1585895011,1.586179e+09,1.586232e+09,"superdome porky k307 libertad, pcgcc sub.bagui...","13th 3616 pilipinas, :1v26 1f-5 (village) bl10...",2020-04-03,2020-04-06,2020-04-07,2,2020-04-07,1,metro manila,metro manila,3,0
3176310,31504462290482,1585826951,1.585965e+09,NaN,galay's 1republic 333-18 diliman 74d malbay fe...,"lane, 379b 1739a ivc afpfc cainta, waterpark, ...",2020-04-02,2020-04-04,NaT,2,None,None,metro manila,metro manila,3,0
3176311,31504851495943,1585891194,1.586230e+09,NaN,"#4560, 80south biloca vi!!age km21, manresa, ,...",lrt-2 consolacion 224-a paradise 6d 36st champ...,2020-04-03,2020-04-07,NaT,3,None,None,luzon,metro manila,5,0
3176312,31505199116340,1585823923,1.586153e+09,1.586231e+09,b4l13 tolda 792-a-5-a east...near carrasco ang...,(jeepney kaligayan vanvan salud asa lauan a-55...,2020-04-02,2020-04-06,2020-04-07,3,2020-04-07,1,luzon,metro manila,5,0

In [37]:
orders.loc[orders['is_late']==1]

,orderid,pick,1st_deliver_attempt,2nd_deliver_attempt,buyeraddress,selleraddress,dt_pick,dt_1st_deliver_attempt,dt_2nd_deliver_attempt,1st_del_busday,dt_2nd_del_att,2nd_del_busday,destination,origin,sla_target,is_late
7,2224695304,1583127841,1.583837e+09,NaN,reel zambo.ciyy puyat.cor road/infront #129a l...,polar 75 mulawinan 1g-3 seÃ±ora text/call 2p-01...,2020-03-02,2020-03-10,NaT,7,None,None,metro manila,metro manila,3,1
19,2227790841,1583127051,1.583823e+09,1.584519e+09,lot16a lgc 833.e danica.. matirem jdel bulango...,"duhat asia, landcom sapang lt25 1015 (kl 294 c...",2020-03-02,2020-03-10,2020-03-18,7,2020-03-18,7,mindanao,metro manila,7,1
21,2227816770,1583119714,1.583470e+09,1.583560e+09,"alejandrea ic-15 building,angliongto ,brgy.pad...",5th redwood fabian k-6th allah rm.405 afpovai ...,2020-03-02,2020-03-06,2020-03-07,4,2020-03-07,1,metro manila,metro manila,3,1
22,2227817800,1583140095,1.583888e+09,NaN,store&first v.ortega purityville leblanc visayas,cmpd. love 2024 package cesar 379b lamar manil...,2020-03-02,2020-03-11,NaT,8,None,None,visayas,metro manila,7,1
24,2227831996,1583117606,1.583469e+09,1.583806e+09,naasag entrance)-seaside 414-c experiment brgy...,"ester omega c.m.recto bebot ususan, name quite...",2020-03-02,2020-03-06,2020-03-10,4,2020-03-10,3,metro manila,metro manila,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3175495,31140751864621,1585377061,1.586158e+09,NaN,"unit.. school,ministop 182a.rivera questhome 1...",427 20e california guazon bernabe kanto)(gray ...,2020-03-28,2020-04-06,NaT,5,None,None,metro manila,metro manila,3,1
3175526,31151634009261,1585385939,1.585978e+09,NaN,kko regus. #31c milibili.proper.roxas.city fel...,898 steeet.pasay chinabank) fb. 1/5th lulu 999...,2020-03-28,2020-04-04,NaT,4,None,None,metro manila,metro manila,3,1
3175569,31188333685284,1585798752,1.586237e+09,NaN,"ivy's building,1967 princepoint topmars paking...","kai (we ""gitna"" mirage bldg,julia ld sis ortiz...",2020-04-02,2020-04-07,NaT,4,None,None,metro manila,metro manila,3,1
3175668,31244254829792,1585820373,1.586225e+09,NaN,bldg.km bridge)panungyan1 street/new pillar co...,"mariveles blg.,alfonso 7-e bukid. ukay 1n15 pa...",2020-04-02,2020-04-07,NaT,4,None,None,metro manila,metro manila,3,1
3175876,31318581682484,1585822427,1.586245e+09,NaN,"engaÃ±o 3432 rizal,poblacion,belison,antique av...",umali -- 1-a stall#u18 layug taft microsourcin...,2020-04-02,2020-04-07,NaT,4,None,None,metro manila,metro manila,3,1

In [38]:
submission = orders[['orderid', 'is_late']].copy()

In [39]:
submission

                orderid  is_late
0            2215676524        0
1            2219624609        0
2            2220979489        0
3            2221066352        0
4            2222478803        0
...                 ...      ...
3176308  31504087640510        0
3176309  31504147352227        0
3176310  31504462290482        0
3176311  31504851495943        0
3176312  31505199116340        0

[3176313 rows x 2 columns]

In [41]:
submission.to_csv('submission1.csv',index=False)